echo "Begin deploy staging"
echo "Begin deploy staging"
echo "Begin deploy staging"
echo "$CI_PULL_REQUEST"
echo "Begin deploy staging"
echo "Begin deploy staging"
echo "$CI_PULL_REQUESTS"
echo "Begin deploy staging"
echo "$CIRCLE_USERNAME"
echo "Begin deploy staging"
echo "$CIRCLE_USERNAME"
echo "Begin deploy staging"